theme: jekyll-theme-slate
title: fcole90
description: Personal profile website
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-mentions
author:
  name: Fabio Colella
  email: fcole90@gmail.com
  github: fcole90
  twitter: fcole1990
